// Generated by https://quicktype.io

export interface Movie {
    id:             number;
    title:          string;
    posterUrl:      string;
    backdropUrl:    null;
    rating:         number;
    overview:       string;
    tagline:        string;
    budget:         number;
    revenue:        number;
    imdbUrl:        null;
    tmdbUrl:        null;
    releaseDate:    string;
    runTime:        number;
    price:          number;
    favoritesCount: number;
    casts:          Cast[];
    genres:         Genre[];
}

export interface Cast {
    id:          number;
    name:        string;
    gender:      null;
    tmdbUrl:     null;
    profilePath: string;
    character:   string;
    movies:      null;
}

export interface Genre {
    id:     number;
    name:   string;
    movies: null;
}
